### ISSUE TITLE
[Request]: Tarball distribution with lzip

### ISSUE THREAD

**Issue by selkfoster** [thkukuk/rpcsvc-proto#10]
Hello!

Thanks for your work on rpcsvc-proto! I wonder if rpcsvc-proto can be distributed using the lzip[1] format.

[1] http://lzip.nongnu.org/

**Comment by thkukuk** [comment]
I provide the three most commonly used formats, I see no sense in adding nearly unused formats. It's only much more work without much benefit.

**Comment by selkfoster** [comment]
Hello @thkukuk,

In fact it is just adding the target "dist-lzip" for "AUTOMAKE_OPTIONS = 1.7 gnits dist-xz" at Makefile.am.

I don't agree with calling lzip "unused", lzip is used for the distribution of the "Time Zone Database[1]" which is no LESS!

Lzip has been designed for long-term archiving, it can also compress more than xz (at the cost of less memory required to decompress a tarball), has a better license, is better maintained than xz, and I don't have to add more since the link I put on the lzip page contains all the necessary information.

[1] https://www.iana.org/time-zones
