### ISSUE TITLE
Unable to compile with musl-1.2.4

### ISSUE THREAD

**Issue by immolo** [thkukuk/rpcsvc-proto#16]
With the recent change to LFS64 in musl-1.2.4 this is unable to compile using that libc. 

Tested on a Gentoo Linux musl system.
[rpcsvc-proto.txt](https://github.com/thkukuk/rpcsvc-proto/files/11426198/rpcsvc-proto.txt)

More information at https://bugs.gentoo.org/905985

**Comment by Kelvium** [comment]
They patched the source, but did not bump the version number. It builds from master.

https://github.com/thkukuk/rpcsvc-proto/commit/28d1adf9209926bc822b338d97c4c99de057a23b

**Comment by immolo** [comment]
Thanks for the help, sent PR for the fix in Gentoo so closing this.

https://github.com/gentoo/gentoo/pull/30960/commits/36e26afd173624f6ecb15ac9a1bae51333fa4852
