### ISSUE TITLE
missing xdr stuff

### ISSUE THREAD

**Issue by red0bear** [thkukuk/rpcsvc-proto#17]
Old versions of rpcgen ccould gen xdr files. since seems distros uses your rpc gen , why rpcgen or repcgen -a doesnt generate all files ?

**Comment by thkukuk** [comment]
> Hello sir, i was trying running old stuff but compiled version debian seems doesnt generate that xdr stuff and after i compiled you source too. If you try just avoid xdr stuff is possible ... but is a bit weird dont generate :

Sorry, I don't understand what you want to tell me with that.

> #This generate a rpcgen -M proto.x

This generates proto_xdr.c. What are you missing?

Please come up with concrete examples in which case what is missing. I cannot see a difference in between which files the old SunRPC rpcgen generates compared with the "new" TI-RPC rpcgen. Beside that the later, newer one has more/different options and uses/generates the newer TI-RPC code, not the already 30 years outdated SunRPC code. Which stopped working latest with IPv6.
