### ISSUE TITLE
which version of libc is required ?

### ISSUE THREAD

**Issue by robinqhuang** [thkukuk/rpcsvc-proto#7]
I got an error of rpcgen during make

I am using libc 2.23

make[2]: Entering directory `rpcsvc-proto-1.4.1/rpcsvc'
../rpcgen/rpcgen -h -o klm_prot.h klm_prot.x
/usr/bin/ld:klm_prot.x: file format not recognized; treating as linker script
/usr/bin/ld:klm_prot.x:39: syntax error
collect2: error: ld returned 1 exit status
../rpcgen/rpcgen: C preprocessor failed with exit code 1

**Comment by thkukuk** [comment]
This has nothing to do with glibc. You seem to have a wired cpp command, why is that calling "ld"?
